# Generated by Django 5.1.6 on 2025-02-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('leito', models.CharField(max_length=20)),
                ('dih', models.CharField(max_length=50)),
                ('diagnostico', models.TextField()),
                ('data_internacao', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('intervencao', models.TextField()),
                ('freq_cardiaca', models.IntegerField()),
                ('freq_respiratoria', models.IntegerField()),
                ('analise', models.TextField()),
                ('av_neuro', models.TextField()),
                ('av_cardio', models.TextField()),
                ('av_resp', models.TextField()),
                ('extras', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='triagem.paciente')),
            ],
        ),
    ]
