# Generated by Django 5.1.6 on 2025-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='analise',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='intervencao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
