# Generated by Django 5.1.6 on 2025-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_remove_avaliacao_analise_remove_paciente_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
